### ISSUE TITLE
12px icons are mostly broken

### ISSUE THREAD

**Issue by nullobject** [Yandrik/embedded-iconoir#5]
I am trying to use the 12px icons in my project, but unfortunately most of them appear fairly broken.

You can see the mangled 12px icons in the example `tester` app:

![Screenshot 2023-12-05 at 12 18 59 pm](https://github.com/Yandrik/embedded-iconoir/assets/3614/2dd08fa3-e402-4651-926a-6de493eaefb1)

Is there any way to improve them?

**Comment by Yandrik** [comment]
The conversion basically works by rendering the SVGs, and then picking all pixels over a certain brightness threshold. So, improving them should be doable by tuning this. I'll look into this when I have time, shouldn't be too hard

**Comment by nullobject** [comment]
@Yandrik Great, thanks. Let me know if you want me to test anything out.

**Comment by Yandrik** [comment]
Took a while because life and such, but here we go: 

![image](https://github.com/Yandrik/embedded-iconoir/assets/12256941/472ef2c7-c2ba-456d-a928-fc74fd522dad)

Here's some severely improved low-res icons. Based on threshold tuning, it's possible to get a little more detail in things like the dots of the church, but that makes the icons seem severely cluttered I think. Here's it with a lower threshold:

![image](https://github.com/Yandrik/embedded-iconoir/assets/12256941/c124b1b1-595f-4b63-970c-e19dcb2d8859)

I'll keep the threshold at 0x40 for now, and push that. Could you try out if that works for you?

**Comment by nullobject** [comment]
Hey thanks @Yandrik, happy new year.

I'll give it a shot and let you know.

**Comment by nullobject** [comment]
I think we can close this ticket when you merge the `lowres_icon_fixes` branch, it looks much better ✅

**Comment by Yandrik** [comment]
New version v0.2.3 with improved icons pushed to crates.io
